### ISSUE TITLE
[FetchIt!] update tables and walls

### ISSUE THREAD

**Issue by moriarty** [fetchrobotics/fetch_gazebo#73]
I'm creating this ticket out of an email from @umhan35 

**Is your feature request related to a problem? Please describe.**
- [ ] The tables locations can be updated
- [x] The logos on the tables can be updated
- [x] More details are now known about the arena walls, they will be 40 inch high and white.

**Describe the solution you'd like**

1. I will get more up to date information about where the tables are located to @RDaneelOlivav 
2. There are 4 tables in the arena, and the machine from SCHUNK #61 two of the tables will have SICK and EandM logos on them @RDaneelOlivav we should discuss via email about putting TheConstruct Logo and Fetch on the other.
3. The walls were used in RoboCup 2018 (same venue as ICRA 2019) but they were the same used in RoboCup 2017 in Japan, They're some sort of standard but I don't know which. They're mainly white with aluminium tops and bottom and aluminium posts, but for the simulation all white should be fine. The walls in our office are made out of white foam-core boards with some metal supports behind them, so the simulation, fetch remote environment and real environment in Montreal will always be a little different but close enough for the robot to be able to navigate.

**Describe alternatives you've considered**
We can just do a bunch of these tickets #61 and #47 all together as one big update.

**Additional context**
We don't have the covers to the tables yet. I was late sending dimension to EandM.
They've ordered them and have provided these files for how the logos will look:
![EandM](https://user-images.githubusercontent.com/55676/55606571-273e0980-572e-11e9-8f51-19447816e993.png)
![SICK](https://user-images.githubusercontent.com/55676/55606576-2a38fa00-572e-11e9-806e-a119dddd904a.png)

Currently the layout looks like this:
![IMG_7917](https://user-images.githubusercontent.com/55676/55606582-302edb00-572e-11e9-9dc7-783609044d40.JPG)

**Comment by RDaneelOlivav** [comment]
OK I have several questions:
1) The tables and their placement: The Table arrangement, location and dimensions are the same as the one we have already in the simulation? The closer they are to the real world the better. The table covers with the logos, I can start working on them. For the Fetch logo could you send which design you want? The tables flat surface will be the WooodDM material that we see or will it have some panel over it? Because I see that the vertical black metal plates protrude around 2cm from the surface, so that could have a huge impact in grasping. 

2) The Walls. In the simulation, only two walls have been placed. So you say that they will be as the ones in Robocup@home competition? What is their height? Will it be even around the entire perimeter or will it be higher on some sides and lower on the others? I suppose the formate you say is this, without logos I suppose or will it have logos of some kind? I'm being really detailed specific because these things can have a huge impact in perception. We want users that have developed their stuff in the ROSject simulations to be able to make the transition to reality as easy as possible.

![watching_gpsr](https://user-images.githubusercontent.com/4933774/55616001-1ecaea80-5791-11e9-923d-d53c4ff50e4b.jpg)

3) I answered in the different issues but, I suppose that the Kit trays we need at least Green, Grey, Yellow, Orange and blue. Also the assembly parts colors, which will they be? Or at least the color assortment so in the simulation, we can even spawn randomly colors objects to train the participants that it could be that way.

4) Also, the lighting conditions are vital. Some time ago we created a ROSject emulating Fetch Domain Randomization Deep Learning paper, we would implement that in the simulation to change slightly the lighting conditions. Let me know what you think: [DomainRandomization](https://www.youtube.com/watch?v=oXsXIia26do&t=242s)

 5) Also reiterate the need to define what exactly does the SHUNK machine do, how it behaves, appearance and so on. I see a @velveteenrobot has created an action client for communicating with the real Shunk but we need to define it in the simulation so people can use it in the same way that in the real place will be used: https://github.com/fetchrobotics/fetch_gazebo/pull/72

**Comment by moriarty** [comment]
I’ll answer in more details when I get to the office:

The tables will be the height we originally sent you, the black bars extend in the photo but I will get white tops for them and the original dimension included the tops.

The side panels with the logos I don’t know the thinkness of, but it might be safe to add 1cm to the dimensions unless we did that originally @velveteenrobot @narora1 ?

The walls will be around most of the arena, with just an opening to get a robot in and out. They are the ones in the photo, and they will only be the short ones- 40 inches tall.

**Comment by moriarty** [comment]
> 1. The tables and their placement: The Table arrangement, location and dimensions are the same as the one we have already in the simulation? The closer they are to the real world the better. The table covers with the logos, I can start working on them. For the Fetch logo could you send which design you want? The tables flat surface will be the WooodDM material that we see or will it have some panel over it? Because I see that the vertical black metal plates protrude around 2cm from the surface, so that could have a huge impact in grasping.

Yes, the original dimensions I sent you was should be just slightly higher than the vertical black posts- I will get tops for the tables this weekend and the tops will be white. When we made the original dimensions we took this into account. The concrete floor where the tables are isn't perfect, so some might be a little tilted but we expect the teams are going to use some sort of **PCL**, **Open3D** or **OpenCV** based detection and segmentation to account for small offsets in the table height.

> 2. The Walls. In the simulation, only two walls have been placed. So you say that they will be as the ones in Robocup@home competition? What is their height? Will it be even around the entire perimeter or will it be higher on some sides and lower on the others? I suppose the formate you say is this, without logos I suppose or will it have logos of some kind? I'm being really detailed specific because these things can have a huge impact in perception. We want users that have developed their stuff in the ROSject simulations to be able to make the transition to reality as easy as possible.

Yes those are the walls, they won't have the logos on the walls (because they're now being provided by and returned to the venue) The logos will be on the front of all the tables. The walls will be all half height - 40 inches tall - like the one in the photo, we won't use the tall walls. The audience will be able to stand around 3 of the sides and should have a clear view of the competition and also see all the logos.

I'm assuming, that teams won't be using visual slam or visual odometry for navigation because of the location of the camera and laser scanner.

> 3. I answered in the different issues but, I suppose that the Kit trays we need at least Green, Grey, Yellow, Orange and blue. Also the assembly parts colors, which will they be? Or at least the color assortment so in the simulation, we can even spawn randomly colors objects to train the participants that it could be that way.

We have Green, Yellow, Blue, Grey, Orange. We ordered the same kit from several different online shops just to see how much they vary in shape and texture. We wanted to verify that if teams go onto an online shop and order a kit it would be close enough to the real thing.

This is related to #47 it would be best to add all colours, we @fetchrobotics/opensource have not had any follow up questions or concerns related to the colour of the kits, but if teams want to vote for one colour then they should have access to all of the colours in the simulator and then we can discuss it later.

> 4. Also, the lighting conditions are vital. Some time ago we created a ROSject emulating Fetch Domain Randomization Deep Learning paper, we would implement that in the simulation to change slightly the lighting conditions. Let me know what you think: [DomainRandomization](https://www.youtube.com/watch?v=oXsXIia26do&t=242s)

Yes, our location in our office was chosen because we can vary the lighting greatly, it's always bright but we have 2 rows of overhead lights and the two walls to the room a complete glass, with white shutters which we can raise/lower. The time of day and if the teams ask us to raise or lower the shutters will make a difference. If it can be varied in the simulation for them to test slightly various conditions that would be great.

We don't know how the lighting will be in Montreal. The location will be in the ground level of the Convention Centre next to the "Lipstick Forest"  so there might also be some natural light.

https://artpublicmontreal.ca/en/oeuvre/lipstick-forest/

At RoboCup 2018 we had the RoboCup@Home Restaurant Test just a little further down the same hallway. 

> 5. Also reiterate the need to define what exactly does the SHUNK machine do, how it behaves, appearance and so on. I see a @velveteenrobot has created an action client for communicating with the real Shunk but we need to define it in the simulation so people can use it in the same way that in the real place will be used: #72

It simply opens and closes the Chuck:
https://schunk.com/us_en/clamping-technology/series/rota-tps/

The teams need to place the Large Gear into the chuck and call the new action from @velveteenrobot which will close/open the chuck.

**Comment by RDaneelOlivav** [comment]
Ok Great answer! Then I'll start working on all this from Wednesday onward, due to other tasks I have. I will start with the environment, tables, and color of elements. Then I'll work on the random lights and other improvements.

**Comment by moriarty** [comment]
![IMG_7948](https://user-images.githubusercontent.com/55676/55742959-f38d0900-59e5-11e9-98f8-dc7aadd1b7b4.JPG)

Sorry I meant to get you the dimensions on Friday, I wrote them down and didn't get a chance to type them up- so I'll just send an image.

The units are centimeters. T1, T2, T3, T4 are the tables which were measured before so I didn't measure them again.

The opening is currently 76cm. The outside is actually 305 x 305 which is 10ft x 10ft, which isn't want the rulebook said- we used meters but the event in Montreal also wanted the arena specified in ft (even though Canada uses metric- it's very mixed because a lot of building supplies are imported or labeled for the US market).

**Comment by RDaneelOlivav** [comment]
Ok , in centimeters is perfect ;)

**Comment by moriarty** [comment]
The signs from SICK & E and M have arrived... I've just put them in place, I'll attach them with Velcro this afternoon.

At the actual event, we will have two arenas. In each arena there will be a table from Fetch, SICK, E and M, TheConstruct ( @RDaneelOlivav SICK & EandM just sent their foam boards with logos to us, you can do the same).... For now, we don't have the signs from Fetch or TheConstruct so I've just put all into the test area.

![IMG_7959](https://user-images.githubusercontent.com/55676/55905182-53221a80-5b86-11e9-862b-9fe61741dc36.JPG)
![IMG_7958](https://user-images.githubusercontent.com/55676/55904025-c37b6c80-5b83-11e9-8e4a-b35d65ff7309.JPG)

**Comment by RDaneelOlivav** [comment]
Great! We will try to send you TheConstruct Image at least. Hope tomorrow have some of the changes for the simulation ;)

**Comment by RDaneelOlivav** [comment]
@moriarty here you have the table image 
[Mesa Fetch 92x78,5 cms.pdf](https://github.com/fetchrobotics/fetch_gazebo/files/3071864/Mesa.Fetch.92x78.5.cms.pdf)

**Comment by RDaneelOlivav** [comment]
I'm working today in the environment disposition, walls and tables

**Comment by RDaneelOlivav** [comment]
@moriarty Just created a pull request with the latest changes regarding this matter: https://github.com/fetchrobotics/fetch_gazebo/pull/78

**Comment by moriarty** [comment]
FYI @frank-qcd-qk

**Comment by ben-fido** [comment]
**Background:**
~~It looks like some of the tables are wider than others. The dimensions in the Gazebo simulation world need to be checked~~.

**Tasks:**
 - ~~Measure the width, depth and height of each table surface and tell us the dimensions?~~
 - ~~Measure the height of the sponsor boards? (it goes higher than the tables)~~
 - Upload image of the artwork for Schunk table with dark-blue background.
 - Update simulation world.  
Arena boundary should be 3.05 x 3.05 square.

.

| Table No.     | Description                   | Width | Depth | Height | Sponsor | Height of sponsor board |
| --------------- | ----------------------------- | -------- | ------- | -------- | ----------- | ------------------- |
| T1                | Screws in green tub     | 0.92 | 0.46 | 0.785 | E and M | 0.80 |
| T2                | Kits                               | 0.92 | 0.46 | 0.785 | Sick |  0.80 |
| T3                | Gearbox parts on table | 0.92 | 0.46 | 0.785 | E and M |  0.80 |
| T4                | Place completed kits     | 0.92 | 0.46 | 0.785 | Sick |  0.80 |
| T5 (Schunk) | Schunk Machine           | 1.10 | 0.70 | 0.795 | Schunk | 0.78 |


All dimensions in meters (SI Units).
.

| Table No. | Photo                                                                                |
| ------------ | ----------------------------------------------------------------------- | 
| T1            | <img src="https://i.imgur.com/kzhSXiG.jpg" width="150"> |
| T2            | <img src="https://i.imgur.com/gkhx2O6.jpg" width="150"> |
| T3            | <img src="https://i.imgur.com/BvedgsJ.jpg" width="150"> |
| T4            | <img src="https://i.imgur.com/YziEpAz.jpg" width="150"> |
| T5            | <img src="https://i.imgur.com/qtRoD6F.jpg" width="150"> |




.

**Comment by ben-fido** [comment]
Thanks @velveteenrobot for check the measurements

**Comment by moriarty** [comment]
We’re expecting that teams will be able to tolerate some small variance in the real and simulated environment.

The real tables in our environment are missing a 3/4 inch top shelf.

**Comment by moriarty** [comment]
Closing this issue as the launch files with “Montreal” in the title are close enough.

**Comment by moriarty** [comment]
We don’t have the artwork for the Schunk Machine.

The logos on the tables will be slightly different in the real vs simulated environment.

**Comment by moriarty** [comment]
FYI- the environment in Montreal will change. But you will have time to update your maps.

**Comment by moriarty** [comment]
@umhan35 - sorry I’m replying to your email here...

Please note the height in the simulation environment was updated when we knew the height of the walls in Montreal, and we never specified the hight of our walls in our remote access environment- they just happened to be made out of material we had on hand, but the simulation environment has the walls at the height which we specified as soon as we knew what it would be with the local on site contractor- and they can not be changed.

The only thing that has changed, is the location of the tables. Because of the material which the walls are built, and the location of the door- we moved the tables slightly. But there will be enough time tomorrow for everyone to build and test two maps: one per arena, and update some pre configured poses.

**Comment by umhan35** [comment]
The walls shouldn’t be a problem for us.
